### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [dstewart97/prj-rev-bwfs-dasmoto#6]
https://github.com/dstewart97/prj-rev-bwfs-dasmoto/blob/master/Art%20%26%20Crafts/index.css#L10

Apply this style to the `h1` tag instead of the surrounding `div` so that it appears as in the design mock.

https://github.com/dstewart97/prj-rev-bwfs-dasmoto/blob/master/Art%20%26%20Crafts/index.css#L13-L32

You're repeating a lot of styles here. Extract the shared styles into a more general selector so that you can eliminate repetition from your code.

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
